# Generated by Django 3.1.7 on 2021-03-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=6)),
                ('lng', models.DecimalField(decimal_places=4, max_digits=7)),
                ('orientation', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('6', '06:00'), ('9', '09:00'), ('12', '12:00'), ('15', '15:00'), ('18', '18:00'), ('21', '21:00')], max_length=5)),
                ('air_temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cloud_cover', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_direction', models.DecimalField(decimal_places=4, max_digits=7)),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.beach')),
            ],
        ),
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('6', '06:00'), ('9', '09:00'), ('12', '12:00'), ('15', '15:00'), ('18', '18:00'), ('21', '21:00')], max_length=5)),
                ('wave_direction', models.DecimalField(decimal_places=4, max_digits=7)),
                ('wave_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wave_period', models.DecimalField(decimal_places=2, max_digits=5)),
                ('water_temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.beach')),
            ],
        ),
        migrations.CreateModel(
            name='Tide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('6', '06:00'), ('9', '09:00'), ('12', '12:00'), ('15', '15:00'), ('18', '18:00'), ('21', '21:00')], max_length=5)),
                ('tide', models.CharField(choices=[('0', 'low'), ('1', 'high')], max_length=5)),
                ('tide_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.beach')),
            ],
        ),
    ]
